#pragma once

// Generated by tools/oracle.py; do not edit by hand.

#include <array>
#include <cstdint>

namespace tensorkiln::oracle_fixture {

inline constexpr std::array<std::int64_t, 2U> kMlpInputShape{{2, 3}};

inline constexpr std::array<std::int64_t, 2U> kMlpWeightShape{{3, 4}};

inline constexpr std::array<std::int64_t, 1U> kMlpBiasShape{{4}};

inline constexpr std::array<std::int64_t, 2U> kMlpOutputShape{{2, 4}};

inline constexpr std::array<float, 6U> kMlpInput{{
    0x1.0000000000000p-1F,
    -0x1.0000000000000p+0F,
    0x1.0000000000000p+1F,
    0x1.8000000000000p+0F,
    0x1.0000000000000p-2F,
    -0x1.8000000000000p-1F,
}};

inline constexpr std::array<float, 12U> kMlpWeights{{
    0x1.0000000000000p-2F,
    -0x1.0000000000000p-1F,
    0x1.0000000000000p+0F,
    0x1.0000000000000p+1F,
    0x1.8000000000000p+0F,
    0x1.8000000000000p-1F,
    -0x1.0000000000000p+0F,
    0x1.0000000000000p-1F,
    -0x1.0000000000000p-2F,
    0x1.0000000000000p+1F,
    0x1.0000000000000p-1F,
    -0x1.8000000000000p+0F,
}};

inline constexpr std::array<float, 4U> kMlpBias{{
    0x1.99999a0000000p-4F,
    -0x1.99999a0000000p-3F,
    0x1.3333340000000p-2F,
    0x1.99999a0000000p-2F,
}};

inline constexpr std::array<float, 8U> kMlpProduct{{
    -0x1.e000000000000p+0F,
    0x1.8000000000000p+1F,
    0x1.4000000000000p+1F,
    -0x1.4000000000000p+1F,
    0x1.e000000000000p-1F,
    -0x1.0800000000000p+1F,
    0x1.c000000000000p-1F,
    0x1.1000000000000p+2F,
}};

inline constexpr std::array<float, 8U> kMlpPreActivation{{
    -0x1.c666660000000p+0F,
    0x1.6666660000000p+1F,
    0x1.6666660000000p+1F,
    -0x1.0ccccc0000000p+1F,
    0x1.09999a0000000p+0F,
    -0x1.21999a0000000p+1F,
    0x1.2ccccc0000000p+0F,
    0x1.29999a0000000p+2F,
}};

inline constexpr std::array<float, 8U> kMlpOutput{{
    0x0.0p+0F,
    0x1.6666660000000p+1F,
    0x1.6666660000000p+1F,
    0x0.0p+0F,
    0x1.09999a0000000p+0F,
    0x0.0p+0F,
    0x1.2ccccc0000000p+0F,
    0x1.29999a0000000p+2F,
}};

}  // namespace tensorkiln::oracle_fixture
