#pragma once

// Generated by tools/softmax_oracle.py; do not edit by hand.
// Expected values use 80-digit Decimal exp and require tolerance checks.
// This corpus is separate from the five-kernel raw-bit fixture.

#include <array>
#include <cstdint>

namespace tensorkiln::softmax_oracle_fixture {

inline constexpr std::array<std::int64_t, 3U> kInputShape{{2, 3, 2}};

inline constexpr std::int64_t kAxis = 1;

inline constexpr std::array<float, 12U> kInput{{
    0.0F,
    2.0F,
    1.0F,
    1.0F,
    2.0F,
    0.0F,
    1000.0F,
    -1.0F,
    1001.0F,
    -1.0F,
    1002.0F,
    -1.0F,
}};

inline constexpr std::array<double, 12U> kExpected{{
    0.090030573170380457998,
    0.66524095577482188953,
    0.24472847105479765247,
    0.24472847105479765247,
    0.66524095577482188953,
    0.090030573170380457998,
    0.090030573170380457998,
    0.33333333333333333333,
    0.24472847105479765247,
    0.33333333333333333333,
    0.66524095577482188953,
    0.33333333333333333333,
}};

}  // namespace tensorkiln::softmax_oracle_fixture
