#!/usr/bin/env python3
"""Generate independent f32 golden fixtures for TensorKiln tests."""

from __future__ import annotations

import argparse
import difflib
import math
import struct
import sys
from collections.abc import Sequence
from pathlib import Path


def f32(value: float) -> float:
    """Round a Python float to IEEE-754 binary32."""
    return struct.unpack("<f", struct.pack("<f", value))[0]


def f32_bits(values: Sequence[float]) -> list[int]:
    return [struct.unpack("<I", struct.pack("<f", value))[0] for value in values]


def require_bits(
    label: str, values: Sequence[float], expected: Sequence[int]
) -> None:
    actual = f32_bits(values)
    if actual != list(expected):
        actual_text = ", ".join(f"{bits:08x}" for bits in actual)
        expected_text = ", ".join(f"{bits:08x}" for bits in expected)
        raise RuntimeError(
            f"{label} bit anchor changed: [{actual_text}] != [{expected_text}]"
        )


def matmul(
    left: Sequence[float],
    right: Sequence[float],
    rows: int,
    inner: int,
    columns: int,
) -> list[float]:
    if len(left) != rows * inner or len(right) != inner * columns:
        raise ValueError("matmul fixture dimensions do not match payloads")

    output: list[float] = []
    for row in range(rows):
        for column in range(columns):
            accumulator = 0.0
            for reduction in range(inner):
                left_value = f32(left[row * inner + reduction])
                right_value = f32(right[reduction * columns + column])
                accumulator += left_value * right_value
            output.append(f32(accumulator))
    return output


def add_last_axis_bias(
    tensor: Sequence[float], bias: Sequence[float]
) -> list[float]:
    if not bias or len(tensor) % len(bias) != 0:
        raise ValueError("bias must cover the final tensor axis")
    return [
        f32(f32(value) + f32(bias[index % len(bias)]))
        for index, value in enumerate(tensor)
    ]


def relu(tensor: Sequence[float]) -> list[float]:
    return [f32(value if f32(value) > 0.0 else 0.0) for value in tensor]


def float_literal(value: float) -> str:
    rounded = f32(value)
    if not math.isfinite(rounded):
        raise ValueError("C++ fixture literals must be finite")
    return rounded.hex() + "F"


def render_float_array(name: str, values: Sequence[float]) -> list[str]:
    lines = [
        f"inline constexpr std::array<float, {len(values)}U> {name}{{{{"
    ]
    lines.extend(f"    {float_literal(value)}," for value in values)
    lines.append("}};")
    return lines


def render_shape(name: str, dimensions: Sequence[int]) -> list[str]:
    values = ", ".join(f"{dimension}" for dimension in dimensions)
    return [
        f"inline constexpr std::array<std::int64_t, {len(dimensions)}U> "
        f"{name}{{{{{values}}}}};"
    ]


def render() -> str:
    inputs = [0.5, -1.0, 2.0, 1.5, 0.25, -0.75]
    weights = [
        0.25,
        -0.5,
        1.0,
        2.0,
        1.5,
        0.75,
        -1.0,
        0.5,
        -0.25,
        2.0,
        0.5,
        -1.5,
    ]
    bias = [0.1, -0.2, 0.3, 0.4]

    product = matmul(inputs, weights, rows=2, inner=3, columns=4)
    pre_activation = add_last_axis_bias(product, bias)
    output = relu(pre_activation)

    require_bits(
        "MLP product",
        product,
        [
            0xBFF00000,
            0x40400000,
            0x40200000,
            0xC0200000,
            0x3F700000,
            0xC0040000,
            0x3F600000,
            0x40880000,
        ],
    )
    require_bits(
        "MLP pre-activation",
        pre_activation,
        [
            0xBFE33333,
            0x40333333,
            0x40333333,
            0xC0066666,
            0x3F84CCCD,
            0xC010CCCD,
            0x3F966666,
            0x4094CCCD,
        ],
    )
    require_bits(
        "MLP output",
        output,
        [
            0x00000000,
            0x40333333,
            0x40333333,
            0x00000000,
            0x3F84CCCD,
            0x00000000,
            0x3F966666,
            0x4094CCCD,
        ],
    )

    sections: list[list[str]] = [
        render_shape("kMlpInputShape", [2, 3]),
        render_shape("kMlpWeightShape", [3, 4]),
        render_shape("kMlpBiasShape", [4]),
        render_shape("kMlpOutputShape", [2, 4]),
        render_float_array("kMlpInput", inputs),
        render_float_array("kMlpWeights", weights),
        render_float_array("kMlpBias", bias),
        render_float_array("kMlpProduct", product),
        render_float_array("kMlpPreActivation", pre_activation),
        render_float_array("kMlpOutput", output),
    ]

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/oracle.py; do not edit by hand.",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace tensorkiln::oracle_fixture {",
        "",
    ]
    for section in sections:
        lines.extend(section)
        lines.append("")
    lines.extend(["}  // namespace tensorkiln::oracle_fixture", ""])
    return "\n".join(lines)


def check_fixture(path: Path, generated: str) -> int:
    try:
        committed = path.read_bytes()
    except OSError as error:
        print(f"oracle: cannot read {path}: {error}", file=sys.stderr)
        return 2

    generated_bytes = generated.encode("utf-8")
    if committed == generated_bytes:
        return 0

    committed_text = committed.decode("utf-8", errors="replace")
    sys.stderr.writelines(
        difflib.unified_diff(
            committed_text.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate independent f32 golden fixtures."
    )
    parser.add_argument(
        "--check",
        metavar="FILE",
        type=Path,
        help="fail unless FILE exactly matches the generated fixture",
    )
    arguments = parser.parse_args()

    generated = render()
    if arguments.check is not None:
        return check_fixture(arguments.check, generated)

    sys.stdout.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
