#!/usr/bin/env python3
"""Generate the independent high-precision Softmax tolerance fixture."""

from __future__ import annotations

import argparse
import difflib
import sys
from collections.abc import Sequence
from decimal import Decimal, localcontext
from pathlib import Path


SHAPE = (2, 3, 2)
AXIS = 1
INPUT = (
    Decimal("0"),
    Decimal("2"),
    Decimal("1"),
    Decimal("1"),
    Decimal("2"),
    Decimal("0"),
    Decimal("1000"),
    Decimal("-1"),
    Decimal("1001"),
    Decimal("-1"),
    Decimal("1002"),
    Decimal("-1"),
)


def softmax(
    tensor: Sequence[Decimal], shape: Sequence[int], axis: int
) -> list[Decimal]:
    """Evaluate mathematical Softmax with deterministic Decimal exponentials."""
    if not shape or any(extent <= 0 for extent in shape):
        raise ValueError("softmax fixture requires a positive-rank shape")
    elements = 1
    for extent in shape:
        elements *= extent
    if len(tensor) != elements:
        raise ValueError("softmax fixture shape does not match its payload")
    if axis < 0:
        axis += len(shape)
    if axis < 0 or axis >= len(shape):
        raise ValueError("softmax fixture axis is out of range")

    axis_extent = shape[axis]
    axis_stride = 1
    for extent in shape[axis + 1 :]:
        axis_stride *= extent
    axis_block = axis_extent * axis_stride
    outer_count = len(tensor) // axis_block
    output = [Decimal(0)] * len(tensor)

    with localcontext() as context:
        context.prec = 80
        for outer in range(outer_count):
            outer_base = outer * axis_block
            for inner in range(axis_stride):
                offsets = [
                    outer_base + coordinate * axis_stride + inner
                    for coordinate in range(axis_extent)
                ]
                maximum = max(tensor[offset] for offset in offsets)
                exponentials = [
                    context.exp(tensor[offset] - maximum)
                    for offset in offsets
                ]
                denominator = sum(exponentials, Decimal(0))
                for offset, exponential in zip(offsets, exponentials):
                    output[offset] = exponential / denominator
    return output


def decimal_literal(value: Decimal) -> str:
    literal = format(value, ".20g").lower()
    if "e" not in literal and "." not in literal:
        literal += ".0"
    return literal


def input_literal(value: Decimal) -> str:
    if value != value.to_integral_value():
        raise ValueError("fixture input must be exactly integral")
    return f"{value:.1f}F"


def render() -> str:
    expected = softmax(INPUT, SHAPE, AXIS)
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/softmax_oracle.py; do not edit by hand.",
        "// Expected values use 80-digit Decimal exp and require tolerance checks.",
        "// This corpus is separate from the five-kernel raw-bit fixture.",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace tensorkiln::softmax_oracle_fixture {",
        "",
        "inline constexpr std::array<std::int64_t, 3U> kInputShape"
        "{{2, 3, 2}};",
        "",
        "inline constexpr std::int64_t kAxis = 1;",
        "",
        "inline constexpr std::array<float, 12U> kInput{{",
    ]
    lines.extend(f"    {input_literal(value)}," for value in INPUT)
    lines.extend(
        [
            "}};",
            "",
            "inline constexpr std::array<double, 12U> kExpected{{",
        ]
    )
    lines.extend(f"    {decimal_literal(value)}," for value in expected)
    lines.extend(
        [
            "}};",
            "",
            "}  // namespace tensorkiln::softmax_oracle_fixture",
            "",
        ]
    )
    return "\n".join(lines)


def check_fixture(path: Path, generated: str) -> int:
    try:
        committed = path.read_bytes()
    except OSError as error:
        print(f"softmax oracle: cannot read {path}: {error}", file=sys.stderr)
        return 2

    generated_bytes = generated.encode("utf-8")
    if committed == generated_bytes:
        return 0

    committed_text = committed.decode("utf-8", errors="replace")
    sys.stderr.writelines(
        difflib.unified_diff(
            committed_text.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile=str(path),
            tofile=f"{path} (generated)",
        )
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate an independent Softmax tolerance fixture."
    )
    parser.add_argument(
        "--check",
        metavar="FILE",
        type=Path,
        help="fail unless FILE exactly matches the generated fixture",
    )
    arguments = parser.parse_args()

    generated = render()
    if arguments.check is not None:
        return check_fixture(arguments.check, generated)

    sys.stdout.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
