#include "tensorkiln/diagnostic.hpp"

namespace tensorkiln {

std::string_view error_code_name(const ErrorCode code) noexcept {
  switch (code) {
    case ErrorCode::rank_limit_exceeded:
      return "rank_limit_exceeded";
    case ErrorCode::extent_not_positive:
      return "extent_not_positive";
    case ErrorCode::element_count_overflow:
      return "element_count_overflow";
    case ErrorCode::element_limit_exceeded:
      return "element_limit_exceeded";
    case ErrorCode::broadcast_incompatible:
      return "broadcast_incompatible";
    case ErrorCode::matmul_rank_unsupported:
      return "matmul_rank_unsupported";
    case ErrorCode::matmul_inner_dimension_mismatch:
      return "matmul_inner_dimension_mismatch";
    case ErrorCode::invalid_name:
      return "invalid_name";
    case ErrorCode::name_limit_exceeded:
      return "name_limit_exceeded";
    case ErrorCode::duplicate_name:
      return "duplicate_name";
    case ErrorCode::value_not_found:
      return "value_not_found";
    case ErrorCode::constant_size_mismatch:
      return "constant_size_mismatch";
    case ErrorCode::graph_node_limit_exceeded:
      return "graph_node_limit_exceeded";
    case ErrorCode::graph_output_limit_exceeded:
      return "graph_output_limit_exceeded";
    case ErrorCode::constant_element_limit_exceeded:
      return "constant_element_limit_exceeded";
    case ErrorCode::graph_has_no_outputs:
      return "graph_has_no_outputs";
    case ErrorCode::builder_finished:
      return "builder_finished";
    case ErrorCode::unsupported_element_type:
      return "unsupported_element_type";
    case ErrorCode::byte_count_overflow:
      return "byte_count_overflow";
    case ErrorCode::byte_limit_exceeded:
      return "byte_limit_exceeded";
    case ErrorCode::input_binding_count_exceeded:
      return "input_binding_count_exceeded";
    case ErrorCode::input_binding_unknown:
      return "input_binding_unknown";
    case ErrorCode::input_binding_duplicate:
      return "input_binding_duplicate";
    case ErrorCode::input_binding_missing:
      return "input_binding_missing";
    case ErrorCode::input_binding_size_mismatch:
      return "input_binding_size_mismatch";
    case ErrorCode::input_binding_aliases_workspace:
      return "input_binding_aliases_workspace";
    case ErrorCode::unsupported_rounding_mode:
      return "unsupported_rounding_mode";
    case ErrorCode::unsupported_binary64_precision:
      return "unsupported_binary64_precision";
    case ErrorCode::unsupported_subnormal_mode:
      return "unsupported_subnormal_mode";
    case ErrorCode::reference_materialization_limit_exceeded:
      return "reference_materialization_limit_exceeded";
    case ErrorCode::reference_scalar_step_limit_exceeded:
      return "reference_scalar_step_limit_exceeded";
    case ErrorCode::compiler_internal_invariant:
      return "compiler_internal_invariant";
    case ErrorCode::provenance_domain_mismatch:
      return "provenance_domain_mismatch";
    case ErrorCode::arena_buffer_limit_exceeded:
      return "arena_buffer_limit_exceeded";
    case ErrorCode::arena_buffer_size_invalid:
      return "arena_buffer_size_invalid";
    case ErrorCode::arena_lifetime_invalid:
      return "arena_lifetime_invalid";
    case ErrorCode::arena_placement_count_mismatch:
      return "arena_placement_count_mismatch";
    case ErrorCode::arena_placement_buffer_not_found:
      return "arena_placement_buffer_not_found";
    case ErrorCode::arena_placement_duplicate:
      return "arena_placement_duplicate";
    case ErrorCode::arena_alignment_invalid:
      return "arena_alignment_invalid";
    case ErrorCode::arena_size_overflow:
      return "arena_size_overflow";
    case ErrorCode::arena_live_overlap:
      return "arena_live_overlap";
    case ErrorCode::arena_workspace_limit_exceeded:
      return "arena_workspace_limit_exceeded";
    case ErrorCode::arena_workspace_unaddressable:
      return "arena_workspace_unaddressable";
    case ErrorCode::plan_value_limit_exceeded:
      return "plan_value_limit_exceeded";
    case ErrorCode::plan_step_limit_exceeded:
      return "plan_step_limit_exceeded";
    case ErrorCode::plan_output_limit_exceeded:
      return "plan_output_limit_exceeded";
    case ErrorCode::plan_constant_byte_limit_exceeded:
      return "plan_constant_byte_limit_exceeded";
    case ErrorCode::plan_work_overflow:
      return "plan_work_overflow";
    case ErrorCode::plan_scalar_step_limit_exceeded:
      return "plan_scalar_step_limit_exceeded";
    case ErrorCode::plan_step_count_mismatch:
      return "plan_step_count_mismatch";
    case ErrorCode::plan_step_source_mismatch:
      return "plan_step_source_mismatch";
    case ErrorCode::plan_kernel_invalid:
      return "plan_kernel_invalid";
    case ErrorCode::plan_kernel_incompatible:
      return "plan_kernel_incompatible";
  }
  return "unknown_error";
}

}  // namespace tensorkiln
